### ISSUE TITLE
Its not working 

### ISSUE THREAD

**Issue by manjisama1** [d0tf/wabox#1]
![Uploading Screenshot_2024-04-16-18-58-00-34_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by d0tf** [comment]
the image is broken

**Comment by manjisama1** [comment]
Its not working and showing this problem

install npm                           ~/wabox     master 
install: missing destination file operand after 'npm'
Try 'install --help' for more information.
 npm install                               ~/wabox     master 
[##################] - reify:node-wav: http fetch GET 200 https://registry.
> sharp@0.32.6 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-android-arm64v8.tar.br
sharp: Installation error: Prebuilt libvips 8.14.5 binaries are not yet available for android-arm64v8
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
[##################] - reify:node-wav: http fetch GET 200 https://registry.
> sharp@0.30.7 install
> (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.12.2/libvips-8.12.2-android-arm64v8.tar.br
sharp: Installation error: Prebuilt libvips 8.12.2 binaries are not yet available for android-arm64v8
sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/wabox/node_modules/wa-sticker-formatter/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)

npm ERR! A complete log of this run can be found in: /data/data/com.termux/files/home/.npm/_logs/2024-04-16T17_33_10_747Z-debug-0.log




![Screenshot_2024-04-16-23-04-09-52_84d3000e3f4017145260f7618db1d683](https://github.com/d0tf/wabox/assets/111729787/06f1cdf7-dfcf-4166-9ba6-c0203ac55aeb)

**Comment by d0tf** [comment]
sharp can't run on android yet, you can run the script on another device like your computer.
